name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature] "
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: Short description of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Opportunity
      description: What problem does this feature solve?
      placeholder: Describe the context or user need

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your idea or suggest an approach

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other info, links, or screenshots?
      placeholder: Optional
